### Checkout [NumPy Documentation](https://numpy.org/doc/stable/)

### NumPy Notes


> - Efficient representation for numbers (floats, ints)
> - NumPy Array is a contiguous and fixed block of memory containing fixed-sized data items. (Like C or Fortran)
> - Operations in NumPy Arrays return a new list. offer immutability

![numpy-arrays](numpyArrays.png)

## Import Packages

In [1]:
import numpy as np

### Create NumPy Arrays: 1-Dimensional

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
# floats
b = np.array([0, .5, 1, 1.5])
b

array([0. , 0.5, 1. , 1.5])

### Accessing & Slicing: 1-Dimensional

In [4]:
# accessing
print(a[0]) 
print(a[1])

1
2


In [5]:
# slicing 

# from 1st till the end (end is implicitly assigned as 4)
print(a[0:])

# from 3rd till the end.
print(a[2:])

# from 2nd till the end. (index = 4 - 1, which is index 3)
print(a[1:4])

[1 2 3 4]
[3 4]
[2 3 4]


In [6]:
# negative slicing
print(a[1:-1])

[2 3]


![PrepInsta Example - Negative Slicing](https://prepinsta.com/wp-content/uploads/2020/08/Slicing-with-Negative-Numbers-in-Python.webp)

In [7]:
# multi-indexing slicing
selected_indices = [0, 2, -1]
a[selected_indices]

array([1, 3, 4])

### Array Datatypes

In [8]:
print(a.dtype)
print(b.dtype)

int32
float64


### Array Shape: (Rows, Columns)

In [9]:
a.shape

(4,)

### Array Size: Total Number of Elements

In [10]:
a.size

4

### Dimensions of NumPy Array

In [11]:
a.ndim

1

### Create NumPy Arrays: 2-Dimensional 
![2D-Numpy](https://www.pythoninformer.com/img/numpy/2d-array-col-1.png)

In [12]:
A = np.array(
    [
        [1, 2, 3], # 0
        [4, 5, 6], # 1
        [7, 8, 9]  # 2
    ])

In [13]:
A.shape

(3, 3)

In [14]:
# total number of elements in A 
A.size

9

In [15]:
# Dimensions in A
A.ndim

2

<img src="https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172112.png" width="300" height="300">

In [16]:
# first row, second column 

# traditional indexing
print(A[0][1])

# numpy indexing in case of 2d arrays
print(A[0, 1])


# second row, first column
print(A[1][0])
print(A[1, 0])

# print second row elements
print(A[1, ])

# from all rows, print second column only
print(A[:, 1])

# from all rows, print third column only
print(A[:, 2])

2
2
4
4
[4 5 6]
[2 5 8]
[3 6 9]


In [17]:
# Rows and Columns in A
A.shape

(3, 3)

### Mutate Data

In [18]:
A[1] = np.array([10, 10 , 10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [19]:
A[2] = 76
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [76, 76, 76]])

### Basic Summary Statistics Methods

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a.sum()

10

In [22]:
a.mean()

2.5

In [23]:
a.std()

1.118033988749895

In [24]:
A = np.array(
    [
        [1, 2, 3], # 0
        [4, 5, 6], # 1
        [7, 8, 9]  # 2
    ])

![Axeses in Python](https://miro.medium.com/max/728/1*6vOXYklmCfYhNIR7ENScYg.png)

In [25]:
print(A.sum(axis = 1))
print(A.sum(axis = 0))

[ 6 15 24]
[12 15 18]


### Vectorized Operations

In [26]:
# arange: from 0 to end (4)
a = np.arange(4)
a

array([0, 1, 2, 3])

In [27]:
# Examples of Vectorized operations
# multiply each number in 'a' by 2
a * 2

array([0, 2, 4, 6])

In [28]:
a + 10

array([10, 11, 12, 13])

In [29]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [30]:
a + b

array([10, 11, 12, 13])

### Boolean Indexing

In [54]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [55]:
a[a > 1]

array([2, 3, 4, 5])

In [56]:
a[a == 3]

array([3])

In [57]:
a[a == 5]

array([5])

In [58]:
a[[True, False, False, True, True, False]]

array([0, 3, 4])

In [59]:
mean = a.mean()
mean

2.5

In [60]:
a[a < mean]

array([0, 1, 2])

### Linear Algebra


In [69]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [70]:
# A dot product B
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [71]:
# A cross product B
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [72]:
# B Transpose
B.T

array([[6, 4, 2],
       [5, 3, 1]])

### Size of objects in Memory

In [76]:
import sys

In [77]:
# size of an integer in python (in bytes)
sys.getsizeof(1)

28

In [80]:
# size of a float in python (in bytes)
sys.getsizeof(1.0)

24

In [78]:
np.dtype(int).itemsize
# just 4 bytes

4

In [79]:
np.dtype(float).itemsize

8